# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - go-task -l
    silent: true

  setup:
    cmds:
      - python3.9 -mvenv .venv
      - .venv/bin/pip install -e yololab
      #- task: download
    status:
      - test -f .venv/bin/yolo

  download:pothole:
    cmds:
      - |
        mkdir -p datasets
        cd datasets
        wget -O tmp.zip https://www.dropbox.com/s/qvglw8pqo16769f/pothole_dataset_v8.zip?dl=1 && unzip tmp.zip && rm tmp.zip
    status:
      - test -f datasets/pothole_dataset_v8/pothole.yaml

  download:fpds:
    cmds:
      - |
        cd datasets
        mkdir -p fpds
        cd fpds
        wget --content-disposition "https://universidaddealcala-my.sharepoint.com/:u:/g/personal/gram_uah_es/EXYxgnEftbtCp2iCgAaWDDQBcAuouxLrV_2kxBDalj3m4w?&Download=1"
        tar xvf test.tar* && rm test.tar*
        wget --content-disposition "https://universidaddealcala-my.sharepoint.com/:u:/g/personal/gram_uah_es/EXQImG_yi5xOifMZYz79_hcBlxATrYEZP5mCu-li4dcWDw?&Download=1"
        tar xvf train.tar* && rm train.tar*
        wget --content-disposition "https://universidaddealcala-my.sharepoint.com/:u:/g/personal/gram_uah_es/EULm_4e4bgBKqnsTxDB5Br4BKf9rApBjYi7T0QrWyJrppw??&Download=1"
        tar xvf valid.tar* && rm valid.tar* 
    status:
      - test -f datasets/fpds/test/split6/split6_002.txt


  train:
    cmds:
      - yolo train data=coco8.yaml model=models/yolov8n.pt epochs=1 lr0=0.01
  
  export:
    cmds:
      - yolo export model=models/yolov8n.pt imgsz=640 format=onnx opset=12

  update:
    cmds:
      - pip install -e yololab


  test:deepsort:
    cmds:
      - python yololab/yololab/experiments/deepsort.py
    
  test:onxx:
    cmds:
      - python yololab/yololab/experiments/onxx.py --model models/yolov8n.onnx --img samples/dogs.webp
